version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    ports: [3000:80]
    volumes:
      - ./videos:/opt/static/videos
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    restart: unless-stopped

  storage:
    image: minio/minio
    command: server /data
    expose: [9000, 9001]
    ports: [9001:9001]
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: test1234
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - storage_data:/data
    extra_hosts:
      # for local testing only, to avoid shadowing by container 'localhost' while console tries to lookup storage.localhost
      - "storage.localhost:host-gateway"
    restart: unless-stopped

volumes:
  storage_data:
